package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.TableArrangement;
import com.google.appinventor.components.runtime.Image;
import com.google.appinventor.components.runtime.Button;
public class Screen3 extends Form implements HandlesEventDispatching {
  private HorizontalArrangement HorizontalArrangement1;
  private TableArrangement TableArrangement1;
  private Image Image1;
  private Image Image2;
  private Image Image3;
  private Image Image4;
  private HorizontalArrangement HorizontalArrangement2;
  private HorizontalArrangement HorizontalArrangement3;
  private HorizontalArrangement HorizontalArrangement4;
  private Button Button1;
  private Button Button2;
  private Button Button3;
  private Button Button4;
  protected void $define() {
    this.AppName("hotel");
    this.BackgroundImage("bg2.jpg");
    this.Title("Screen3");
    HorizontalArrangement1 = new HorizontalArrangement(this);
    TableArrangement1 = new TableArrangement(HorizontalArrangement1);
    TableArrangement1.Columns(3);
    TableArrangement1.Height(LENGTH_FILL_PARENT);
    TableArrangement1.Width(LENGTH_FILL_PARENT);
    TableArrangement1.Rows(8);
    Image1 = new Image(TableArrangement1);
    Image1.Column(0);
    Image1.Height(-1035);
    Image1.Width(-1040);
    Image1.Picture("download.jpg");
    Image1.Row(0);
    Image1.ScalePictureToFit(true);
    Image2 = new Image(TableArrangement1);
    Image2.Column(2);
    Image2.Height(-1035);
    Image2.Width(-1045);
    Image2.Picture("taj-palace-mumbai.jpg");
    Image2.Row(0);
    Image2.ScalePictureToFit(true);
    Image3 = new Image(TableArrangement1);
    Image3.Column(0);
    Image3.Height(-1035);
    Image3.Width(-1040);
    Image3.Picture("taj-falaknuma-palace.jpg");
    Image3.Row(2);
    Image3.ScalePictureToFit(true);
    Image4 = new Image(TableArrangement1);
    Image4.Column(2);
    Image4.Height(-1035);
    Image4.Width(-1045);
    Image4.Picture("lake-palace-jaipur.jpg");
    Image4.Row(2);
    Image4.ScalePictureToFit(true);
    HorizontalArrangement2 = new HorizontalArrangement(TableArrangement1);
    HorizontalArrangement2.Column(1);
    HorizontalArrangement2.Width(15);
    HorizontalArrangement2.Row(0);
    HorizontalArrangement3 = new HorizontalArrangement(TableArrangement1);
    HorizontalArrangement3.Column(1);
    HorizontalArrangement3.Height(15);
    HorizontalArrangement3.Width(15);
    HorizontalArrangement3.Row(1);
    HorizontalArrangement4 = new HorizontalArrangement(TableArrangement1);
    HorizontalArrangement4.Column(1);
    HorizontalArrangement4.Width(10);
    HorizontalArrangement4.Row(2);
    Button1 = new Button(TableArrangement1);
    Button1.BackgroundColor(0x00FFFFFF);
    Button1.Column(0);
    Button1.FontSize(18);
    Button1.Row(1);
    Button1.Shape(3);
    Button1.Text("Oberoi Hotels");
    Button2 = new Button(TableArrangement1);
    Button2.BackgroundColor(0x00FFFFFF);
    Button2.Column(2);
    Button2.FontSize(18);
    Button2.Row(1);
    Button2.Shape(3);
    Button2.Text("Taj Palace");
    Button3 = new Button(TableArrangement1);
    Button3.BackgroundColor(0x00FFFFFF);
    Button3.Column(0);
    Button3.FontSize(16);
    Button3.Row(3);
    Button3.Shape(3);
    Button3.Text("Taj-Falaknuma-palace");
    Button4 = new Button(TableArrangement1);
    Button4.BackgroundColor(0x00FFFFFF);
    Button4.Column(2);
    Button4.FontSize(18);
    Button4.Row(3);
    Button4.Shape(3);
    Button4.Text("Lake-palace");
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}