package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.VerticalArrangement;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.TableArrangement;
import com.google.appinventor.components.runtime.TextBox;
import com.google.appinventor.components.runtime.PasswordTextBox;
import com.google.appinventor.components.runtime.Button;
import com.google.appinventor.components.runtime.FirebaseDB;
public class Screen1 extends Form implements HandlesEventDispatching {
  private VerticalArrangement VerticalArrangement1;
  private HorizontalArrangement HorizontalArrangement7;
  private Label Label3;
  private TableArrangement TableArrangement1;
  private HorizontalArrangement HorizontalArrangement1;
  private HorizontalArrangement HorizontalArrangement2;
  private HorizontalArrangement HorizontalArrangement3;
  private HorizontalArrangement HorizontalArrangement4;
  private Label Label1;
  private Label label_password;
  private TextBox mobile;
  private PasswordTextBox password;
  private HorizontalArrangement HorizontalArrangement5;
  private Button Button1;
  private HorizontalArrangement HorizontalArrangement6;
  private Button Button2;
  private Label Label2;
  private FirebaseDB FirebaseDB1;
  protected void $define() {
    this.AppName("hotel");
    this.BackgroundImage("bg2.jpg");
    this.Icon("hotel-flat-icon-vector.jpg");
    this.Title("Screen1");
    VerticalArrangement1 = new VerticalArrangement(this);
    VerticalArrangement1.AlignHorizontal(3);
    VerticalArrangement1.AlignVertical(2);
    VerticalArrangement1.Height(-1032);
    VerticalArrangement1.Width(LENGTH_FILL_PARENT);
    HorizontalArrangement7 = new HorizontalArrangement(VerticalArrangement1);
    HorizontalArrangement7.AlignHorizontal(3);
    HorizontalArrangement7.AlignVertical(2);
    HorizontalArrangement7.Height(LENGTH_FILL_PARENT);
    Label3 = new Label(HorizontalArrangement7);
    Label3.FontBold(true);
    Label3.FontItalic(true);
    Label3.FontSize(25);
    Label3.Height(LENGTH_FILL_PARENT);
    Label3.Width(LENGTH_FILL_PARENT);
    Label3.Text("Welcome Hotel Booking APP");
    TableArrangement1 = new TableArrangement(this);
    TableArrangement1.Columns(4);
    TableArrangement1.Width(LENGTH_FILL_PARENT);
    HorizontalArrangement1 = new HorizontalArrangement(TableArrangement1);
    HorizontalArrangement1.Column(0);
    HorizontalArrangement1.Width(-1007);
    HorizontalArrangement1.Row(1);
    HorizontalArrangement2 = new HorizontalArrangement(TableArrangement1);
    HorizontalArrangement2.Column(0);
    HorizontalArrangement2.Width(-1007);
    HorizontalArrangement2.Row(0);
    HorizontalArrangement3 = new HorizontalArrangement(TableArrangement1);
    HorizontalArrangement3.Column(3);
    HorizontalArrangement3.Width(-1010);
    HorizontalArrangement3.Row(0);
    HorizontalArrangement4 = new HorizontalArrangement(TableArrangement1);
    HorizontalArrangement4.Column(3);
    HorizontalArrangement4.Width(-1010);
    HorizontalArrangement4.Row(1);
    Label1 = new Label(TableArrangement1);
    Label1.Column(1);
    Label1.FontBold(true);
    Label1.FontSize(20);
    Label1.Row(0);
    Label1.Text("MOBILE");
    label_password = new Label(TableArrangement1);
    label_password.Column(1);
    label_password.FontBold(true);
    label_password.FontSize(20);
    label_password.Row(1);
    label_password.Text("PASSWORD");
    mobile = new TextBox(TableArrangement1);
    mobile.Column(2);
    mobile.Hint("Enter registered mobile");
    mobile.Row(0);
    password = new PasswordTextBox(TableArrangement1);
    password.Column(2);
    password.Hint("Enter password");
    password.Row(1);
    HorizontalArrangement5 = new HorizontalArrangement(this);
    HorizontalArrangement5.Width(LENGTH_FILL_PARENT);
    Button1 = new Button(HorizontalArrangement5);
    Button1.FontBold(true);
    Button1.FontSize(20);
    Button1.Text("LOGIN");
    HorizontalArrangement6 = new HorizontalArrangement(HorizontalArrangement5);
    HorizontalArrangement6.Height(LENGTH_FILL_PARENT);
    Button2 = new Button(HorizontalArrangement5);
    Button2.FontBold(true);
    Button2.FontSize(20);
    Button2.Text("REGISTER");
    Label2 = new Label(this);
    Label2.FontSize(20);
    FirebaseDB1 = new FirebaseDB(this);
    FirebaseDB1.FirebaseToken(eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzI2MTAzOTI4LCJ2IjowLCJkIjp7InVpZCI6ImE4MjU2YmNjLWU1MWUtNDdmZi04NDY2LTliMDc2YmVjNTk4NyIsInByb2plY3QiOiJob3RlbCIsImRldmVsb3BlciI6InJ2Z29mbXlzQGdtYWlsOmNvbSJ9LCJpYXQiOjE1MTU2NDMxMjh9.TGwnvDhlEW2gfF1wqhAWpJRa1IuEhy-ycP5pDq0Vp4E);
    FirebaseDB1.FirebaseURL(https://rvgofmys-93f1e.firebaseio.com/);
    FirebaseDB1.ProjectBucket(hotel);
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}