package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.VerticalArrangement;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.TableArrangement;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.TextBox;
import com.google.appinventor.components.runtime.Button;
import com.google.appinventor.components.runtime.PasswordTextBox;
import com.google.appinventor.components.runtime.FirebaseDB;
public class Screen2 extends Form implements HandlesEventDispatching {
  private VerticalArrangement VerticalArrangement1;
  private HorizontalArrangement HorizontalArrangement1;
  private HorizontalArrangement HorizontalArrangement2;
  private TableArrangement TableArrangement1;
  private Label Label1;
  private TextBox username;
  private TextBox mobile;
  private Button Button1;
  private Label Label3;
  private PasswordTextBox password;
  private Label Label4;
  private TextBox email;
  private Button Button2;
  private Label Label2;
  private HorizontalArrangement HorizontalArrangement3;
  private Label notifier;
  private FirebaseDB FirebaseDB1;
  protected void $define() {
    this.AppName("hotel");
    this.BackgroundImage("JHYTI.jpg");
    this.Title("Screen2");
    VerticalArrangement1 = new VerticalArrangement(this);
    HorizontalArrangement1 = new HorizontalArrangement(this);
    HorizontalArrangement1.Width(LENGTH_FILL_PARENT);
    HorizontalArrangement2 = new HorizontalArrangement(HorizontalArrangement1);
    HorizontalArrangement2.Width(-1006);
    TableArrangement1 = new TableArrangement(HorizontalArrangement1);
    TableArrangement1.Rows(5);
    Label1 = new Label(TableArrangement1);
    Label1.Column(0);
    Label1.FontBold(true);
    Label1.FontSize(20);
    Label1.Row(0);
    Label1.Text("USERNAME");
    username = new TextBox(TableArrangement1);
    username.Column(1);
    username.Hint("Enter UserName");
    username.Row(0);
    mobile = new TextBox(TableArrangement1);
    mobile.Column(1);
    mobile.Hint("Enter Mobile Number");
    mobile.Row(1);
    Button1 = new Button(TableArrangement1);
    Button1.Column(0);
    Button1.FontSize(20);
    Button1.Row(4);
    Button1.Shape(3);
    Button1.Text("REGISTER");
    Label3 = new Label(TableArrangement1);
    Label3.Column(0);
    Label3.FontBold(true);
    Label3.FontSize(20);
    Label3.Row(3);
    Label3.Text("PASSWORD");
    password = new PasswordTextBox(TableArrangement1);
    password.Column(1);
    password.Hint("Enter Password");
    password.Row(3);
    Label4 = new Label(TableArrangement1);
    Label4.Column(0);
    Label4.FontBold(true);
    Label4.FontSize(20);
    Label4.Row(2);
    Label4.Text("Email");
    email = new TextBox(TableArrangement1);
    email.Column(1);
    email.Hint("Enter Email");
    email.Row(2);
    Button2 = new Button(TableArrangement1);
    Button2.Column(1);
    Button2.FontSize(20);
    Button2.Row(4);
    Button2.Shape(3);
    Button2.Text("LOGIN");
    Label2 = new Label(TableArrangement1);
    Label2.Column(0);
    Label2.FontBold(true);
    Label2.FontSize(20);
    Label2.Row(1);
    Label2.Text("MOBILE");
    HorizontalArrangement3 = new HorizontalArrangement(HorizontalArrangement1);
    HorizontalArrangement3.Width(-1010);
    notifier = new Label(this);
    notifier.FontSize(20);
    FirebaseDB1 = new FirebaseDB(this);
    FirebaseDB1.FirebaseToken(eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzI2Mjk2OTUyLCJ2IjowLCJkIjp7InVpZCI6IjY0ODUzMWNhLTUzYTYtNDkwMC05MDk3LTAzMmJlZTEzMzIwNiIsInByb2plY3QiOiIiLCJkZXZlbG9wZXIiOiJydmdvZm15c0BnbWFpbDpjb20ifSwiaWF0IjoxNTE1ODM2MTUyfQ.EI6C_m2e4P3nT3fJRWsF_RWY7e_ECYc6a8-IxNDdHKU);
    FirebaseDB1.FirebaseURL(https://rvgofmys-93f1e.firebaseio.com/);
    FirebaseDB1.ProjectBucket(hotel);
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}