package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.TableArrangement;
import com.google.appinventor.components.runtime.DatePicker;
import com.google.appinventor.components.runtime.TextBox;
import com.google.appinventor.components.runtime.Button;
import com.google.appinventor.components.runtime.Spinner;
import com.google.appinventor.components.runtime.Texting;
import com.google.appinventor.components.runtime.PhoneCall;
import android.content.Intent;
public class Screen4 extends Form implements HandlesEventDispatching {
  private HorizontalArrangement HorizontalArrangement1;
  private Label Label1;
  private HorizontalArrangement HorizontalArrangement2;
  private Label Label2;
  private HorizontalArrangement HorizontalArrangement3;
  private Label Label3;
  private HorizontalArrangement HorizontalArrangement4;
  private TableArrangement TableArrangement1;
  private Label Label4;
  private Label Label5;
  private DatePicker Date;
  private Label Label6;
  private TextBox number_of_rooms;
  private Label Label7;
  private Label Label8;
  private TextBox Phone;
  private TextBox name;
  private Button Button1;
  private Button Button2;
  private Spinner Spinner1;
  private Texting Texting1;
  private PhoneCall PhoneCall1;
  protected void $define() {
    this.AppName("hotel");
    this.BackgroundImage("bg2.jpg");
    this.Title("Screen4");
    HorizontalArrangement1 = new HorizontalArrangement(this);
    HorizontalArrangement1.AlignHorizontal(3);
    HorizontalArrangement1.AlignVertical(2);
    HorizontalArrangement1.Width(LENGTH_FILL_PARENT);
    Label1 = new Label(HorizontalArrangement1);
    Label1.FontBold(true);
    Label1.FontItalic(true);
    Label1.FontSize(20);
    Label1.FontTypeface(1);
    Label1.Text("Oberoi Hotel");
    HorizontalArrangement2 = new HorizontalArrangement(this);
    HorizontalArrangement2.AlignHorizontal(3);
    HorizontalArrangement2.AlignVertical(2);
    HorizontalArrangement2.BackgroundColor(0x00FFFFFF);
    HorizontalArrangement2.Width(LENGTH_FILL_PARENT);
    Label2 = new Label(HorizontalArrangement2);
    Label2.Text(" High speed Internet access for up to four devices");
    HorizontalArrangement3 = new HorizontalArrangement(this);
    HorizontalArrangement3.AlignHorizontal(3);
    HorizontalArrangement3.AlignVertical(2);
    HorizontalArrangement3.Width(LENGTH_FILL_PARENT);
    Label3 = new Label(HorizontalArrangement3);
    Label3.Text("an iPad interface allows guests to manage everything ");
    HorizontalArrangement4 = new HorizontalArrangement(this);
    HorizontalArrangement4.Height(LENGTH_FILL_PARENT);
    HorizontalArrangement4.Width(LENGTH_FILL_PARENT);
    TableArrangement1 = new TableArrangement(HorizontalArrangement4);
    TableArrangement1.Height(LENGTH_FILL_PARENT);
    TableArrangement1.Width(LENGTH_FILL_PARENT);
    TableArrangement1.Rows(7);
    Label4 = new Label(TableArrangement1);
    Label4.Column(0);
    Label4.FontBold(true);
    Label4.FontItalic(true);
    Label4.FontSize(20);
    Label4.Row(0);
    Label4.Text("Type of Room");
    Label5 = new Label(TableArrangement1);
    Label5.Column(0);
    Label5.FontBold(true);
    Label5.FontItalic(true);
    Label5.FontSize(20);
    Label5.Row(1);
    Label5.Text("      Date");
    Date = new DatePicker(TableArrangement1);
    Date.Column(1);
    Date.FontSize(14);
    Date.Row(1);
    Date.Text("Pick Date");
    Label6 = new Label(TableArrangement1);
    Label6.Column(0);
    Label6.FontBold(true);
    Label6.FontItalic(true);
    Label6.FontSize(20);
    Label6.Row(2);
    Label6.Text("Number of Rooms");
    number_of_rooms = new TextBox(TableArrangement1);
    number_of_rooms.Column(1);
    number_of_rooms.Hint("Number of Rooms");
    number_of_rooms.NumbersOnly(true);
    number_of_rooms.Row(2);
    Label7 = new Label(TableArrangement1);
    Label7.Column(0);
    Label7.FontBold(true);
    Label7.FontItalic(true);
    Label7.FontSize(20);
    Label7.Row(3);
    Label7.Text("Name");
    Label8 = new Label(TableArrangement1);
    Label8.Column(0);
    Label8.FontBold(true);
    Label8.FontItalic(true);
    Label8.FontSize(20);
    Label8.Row(4);
    Label8.Text("Phone Number");
    Phone = new TextBox(TableArrangement1);
    Phone.Column(1);
    Phone.Hint("Enter your number");
    Phone.NumbersOnly(true);
    Phone.Row(4);
    name = new TextBox(TableArrangement1);
    name.Column(1);
    name.Hint("Enter your name");
    name.Row(3);
    Button1 = new Button(TableArrangement1);
    Button1.Column(0);
    Button1.Height(30);
    Button1.Width(30);
    Button1.Image("Book-Now-Button-Transparent-PNG.png");
    Button1.Row(6);
    Button1.Shape(1);
    Button2 = new Button(TableArrangement1);
    Button2.Column(1);
    Button2.FontBold(true);
    Button2.FontSize(18);
    Button2.Row(6);
    Button2.Shape(1);
    Button2.Text("Logout");
    Spinner1 = new Spinner(TableArrangement1);
    Spinner1.Column(1);
    Spinner1.ElementsFromString("Standard room,Deluxe Room");
    Spinner1.Prompt("Standard room");
    Spinner1.Row(0);
    Texting1 = new Texting(this);
    PhoneCall1 = new PhoneCall(this);
    EventDispatcher.registerEventForDelegation(this, "ClickEvent", "Click" );
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    if( component.equals(Button1) && eventName.equals("Click") ){
      Button1Click();
      return true;
    }
    if( component.equals(Button2) && eventName.equals("Click") ){
      Button2Click();
      return true;
    }
    return false;
  }
  public void Button1Click(){
    if(Integer.valueOf(number_of_rooms.Text())<5){
      Texting1.PhoneNumber(Phone.Text());
      Texting1.Message(" Hello" + name.Text() + "  you have booked" + number_of_rooms.Text() + " rooms of type " + Spinner1.Selection() + "  on " + Date.Day() + Date.MonthInText() + Date.Year() + "     " + "     " + "Thankk you" + "     ");
    }
  }
  public void Button2Click(){
    startActivity(new Intent().setClass(this, Screen1.class));
  }
}